### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by blond** [gulp-bem/gulp-bem#21]
Let's all make some logos!

I'll add add already existing logos so we'll be able to vote for them.

Suggest your ideas and comment existing logos.

**Comment by blond** [comment]
![111](https://cloud.githubusercontent.com/assets/2225579/15871110/9a04af92-2cfb-11e6-906f-46f71e34d244.png)

**Comment by blond** [comment]
![222](https://cloud.githubusercontent.com/assets/2225579/15871115/a02a95da-2cfb-11e6-8769-25af843b2c07.png)

**Comment by blond** [comment]
![333](https://cloud.githubusercontent.com/assets/2225579/15871137/b23bb33a-2cfb-11e6-8b46-a12adc9d486a.png)

**Comment by blond** [comment]
![444](https://cloud.githubusercontent.com/assets/2225579/15871143/ba90c926-2cfb-11e6-9384-300d30d4d2a1.png)

**Comment by blond** [comment]
![555](https://cloud.githubusercontent.com/assets/2225579/15871148/bf7bc99a-2cfb-11e6-9c30-a55d42e0b463.png)

**Comment by voischev** [comment]
так это.. тут @Yeti-or говорит что галп уже не использует стакан с трубкой в качестве лого.

**Comment by blond** [comment]
@voischev, так никто кроме галпа об этом и не знает ;) 

Узнаваемость осталась же.
