### ISSUE TITLE
Order of levels is not guaranteed

### ISSUE THREAD

**Issue by incrop** [gulp-bem/gulp-bem#9]
```javascript
var project = bem({
    bemconfig: {
        // These should probably be members of array, not object
        'common.blocks': { scheme: 'nested' },
        'desktop.blocks': { scheme: 'nested' }
    }
});
```

**Comment by blond** [comment]
The [bem-config](https://github.com/bem-contrib/bem-config) should not contains info about order to build. It helps to talk about `scheme`, `naming` and other info about level.

We should specify order to build bundle. Each bundle can consist of different set of levels.

For example:

```js
bem.src({
    levels: ['level1', 'level2'],
    extensions: ['.bemhtml.js', '.bemhtml']
});
```

**Comment by zxqfox** [comment]
@incrop Feel free to reopen
